name: Autograding

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Maven wrapper
        run: |
          chmod +x mvnw
          ./mvnw --version

      - name: Compile code
        run: ./mvnw clean compile
        timeout-minutes: 5

      - name: Run tests
        run: ./mvnw test
        timeout-minutes: 5

      - name: Generate test report
        if: always()
        run: |
          if [ -d "target/surefire-reports" ]; then
            echo "## Test Results" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY

            # Count test results
            TOTAL=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -oP 'tests="\K[0-9]+' {} \; | awk '{s+=$1} END {print s}')
            FAILURES=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -oP 'failures="\K[0-9]+' {} \; | awk '{s+=$1} END {print s}')
            ERRORS=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -oP 'errors="\K[0-9]+' {} \; | awk '{s+=$1} END {print s}')
            SKIPPED=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -oP 'skipped="\K[0-9]+' {} \; | awk '{s+=$1} END {print s}')

            # Default to 0 if empty
            TOTAL=${TOTAL:-0}
            FAILURES=${FAILURES:-0}
            ERRORS=${ERRORS:-0}
            SKIPPED=${SKIPPED:-0}
            PASSED=$((TOTAL - FAILURES - ERRORS - SKIPPED))

            echo "- **Total Tests:** $TOTAL" >> $GITHUB_STEP_SUMMARY
            echo "- **Passed:** ✅ $PASSED" >> $GITHUB_STEP_SUMMARY
            echo "- **Failed:** ❌ $FAILURES" >> $GITHUB_STEP_SUMMARY
            echo "- **Errors:** ⚠️ $ERRORS" >> $GITHUB_STEP_SUMMARY
            echo "- **Skipped:** ⏭️ $SKIPPED" >> $GITHUB_STEP_SUMMARY

            if [ "$FAILURES" -eq 0 ] && [ "$ERRORS" -eq 0 ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### 🎉 All tests passed!" >> $GITHUB_STEP_SUMMARY
            else
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### ❌ Some tests failed. Please review the output above." >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "⚠️ No test reports found" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
          retention-days: 30

      - name: Check test success
        if: success()
        run: |
          echo "✅ All tests passed successfully!"
          echo "Your BoundedBuffer implementation is correct."

      - name: Check test failure
        if: failure()
        run: |
          echo "❌ Tests failed. Please review the errors above and fix your implementation."
          exit 1
